---
title: "Commodity Price of Beef"
output: pdf_document
date: "2022-12-05"
---


```{r}
library(readxl)
library(astsa)
library(fpp2)
library(tseries)
```

```{r}
beef = read_excel("beef-120.xlsx")
train=beef[1:115,]
test=beef[-(1:115),]
tsplot(beef$Price)
```

```{r}
par(mfrow=c(3,1))
tsplot(train$Price)
acf(train$Price)
pacf(train$Price)
```


```{r}
diff.beef = diff(train$Price)
par(mfrow=c(3,1))
tsplot(diff.beef)
acf(diff.beef)
pacf(diff.beef)
```

```{r}
adf.test(train$Price) # not stationary
kpss.test(train$Price, null="Trend") # not trend stationary
```


```{r}
adf.test(diff(train$Price)) # stationary
kpss.test(diff(train$Price), null="Trend") # trend stationary
```

```{r}
par(mfrow=c(2,1))
mvspec(diff(train$Price))
train.spec=mvspec(diff(train$Price), spans=c(3,3), log="no", taper=.5,lwd=2,col='blue')
abline(v=c(.035,0.1), lty=2)
```

```{r}
train.spec$details
```

```{r}
df=train.spec$df
U = qchisq(.025, df)
L = qchisq(.975, df)
train.spec$spec[4];train.spec$spec[12]
df*train.spec$spec[4]/L;df*train.spec$spec[4]/U
```


```{r}
diff.beef10 = diff(diff(train$Price,10))
par(mfrow=c(3,1))
tsplot(diff.beef10)
acf(diff.beef10, lag.max = 50) # The seasonal ACF cuts off after lag 9. The nonseasonal ACF cuts off after lag 2.
pacf(diff.beef10,lag.max = 50) # The seasonal PACF tails off. The nonseasonal PACF tails off.
```

```{r}
adf.test(diff.beef10) # stationary
kpss.test(diff.beef10, null="Trend") # trend stationary
```


```{r}
auto.arima(diff.beef10)
```


```{r}
sarima(train$Price,p=0, d=1, q=2, P=0, D=1, Q=9, S=10)
train.model.1 = sarima.for(train$Price,p=0, d=1, q=2, P=0, D=1, Q=9, S=10, n.ahead = 5)
accuracy(object = train.model.1$pred, x=test$Price)
```


```{r}
sarima(train$Price,p=0, d=1, q=1, P=0, D=1, Q=1, S=10)
train.model.1.1 = sarima.for(train$Price,p=0, d=1, q=1, P=0, D=1, Q=1, S=10, n.ahead = 5)
train.model.1.1$pred
accuracy(object = train.model.1.1$pred, x=test$Price)
```

